wandb_version: 1

global_layer_aggregation:
  desc: null
  value: mean
layer_aggregation:
  desc: null
  value: mean
lr:
  desc: null
  value: 0.001
model:
  desc: null
  value:
    conv_layer_dropout: 0.1
    linear_layer_dropout: 0.25
    no_hidden_units: 80
no_epochs:
  desc: null
  value: 100
train_batch_size:
  desc: null
  value: 512
weight_decay:
  desc: null
  value: 0.015022427634141904
_wandb:
  desc: null
  value:
    python_version: 3.10.8
    cli_version: 0.15.12
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1714024320.45039
    t:
      1:
      - 1
      - 55
      - 77
      2:
      - 1
      - 55
      - 77
      3:
      - 2
      - 23
      - 37
      4: 3.10.8
      5: 0.15.12
      8:
      - 3
      - 5
      13: windows-amd64
