wandb_version: 1

global_layer_aggregation:
  value: mean
layer_aggregation:
  value: max
lr:
  value: 0.001
model:
  value:
    conv_layer_dropout: 0.1
    linear_layer_dropout: 0.25
    no_hidden_units: 80
no_epochs:
  value: 3
train_batch_size:
  value: 64
weight_decay:
  value: 0.01
